// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deowszajnzvpxjwvonzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlb3dzemFqbnp2cHhqd3ZvbnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MTMxNDQsImV4cCI6MjA1MDE4OTE0NH0.M6wPcqkChFHnrFcovtyPbASm3EFQWO2PK8M9bWFoZSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);